---
# yamllint disable rule:line-length
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: examples/
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - --autofix
      - id: detect-aws-credentials
      - id: detect-private-key
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-tabs
        exclude_types: [ python, javascript, dtd, markdown, makefile, xml ]
        exclude: binary|\.bin$|rego|\.rego$|go|\.go$
  - repo: https://github.com/jameswoolfenden/pre-commit-shell
    rev: 0.0.2
    hooks:
      - id: shell-lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        exclude: src/testdata|testdata
  - repo: https://github.com/jameswoolfenden/pre-commit
    rev: v0.1.50
    hooks:
      - id: terraform-fmt
        language_version: python3.11
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: gofmt
      - id: goimports
        exclude: src/parse/terraform-provider-*
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: go-test
        args: [ "./..." ]
      - id: go-mod-tidy
      - id: go-generate
  - repo: https://github.com/jameswoolfenden/ghat
    rev: v0.1.3
    hooks:
      - id: ghat-go
        name: ghat
        description: upgrade action dependencies
        language: golang
        entry: ghat swot -d . --continue-on-error true --stable 14
        always_run: true
        pass_filenames: false
        types: [ yaml ]
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: validate-toml
      - id: no-go-testing
      - id: go-mod-tidy
